---
- name: Disable swap memory
  include_tasks: swap.yml
  tags: swap

- name: Configure SELinux to permissive mode
  include_tasks: selinux.yml
  tags: selinux

- name: Configure firewall ports
  include_tasks: firewall.yml
  tags: firewall

- name: Load kernel modules
  include_tasks: kernel_modules.yml
  tags: kernel_modules

- name: Configure sysctl parameters
  include_tasks: sysctl.yml
  tags: sysctl

- name: Setup NTP time synchronization
  include_tasks: ntp.yml
  tags: ntp

- name: Configure hostname and hosts file
  include_tasks: hostname.yml
  tags: hostname
