---
- name: Set SELinux permissive mode
  command: setenforce 0
  when: ansible_selinux.status == "enabled" and ansible_selinux.mode != "permissive"
  failed_when: false

- name: Set SELinux permissive mode permanently
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=permissive'
  when: ansible_selinux.status == "enabled"

- name: Verify SELinux mode
  command: getenforce
  register: selinux_status
  changed_when: false
