---
- name: Off swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Remove swap from fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^\s*[^#].*\sswap\s'
    state: absent
  register: fstab_modified

- name: Verify swap is disabled
  command: swapon --show
  register: swap_status
  changed_when: false
  failed_when: swap_status.stdout != ""
